# =============================================================================
# ThreadX Middleware Library
# =============================================================================
set(THREADX_ROOT "${STM32CUBE_ROOT}/Middlewares/ST/threadx")

set(THREADX_SOURCES
    ${THREADX_ROOT}/ports/cortex_m55/gnu/src/tx_thread_secure_stack_initialize.S
    ${THREADX_ROOT}/ports/cortex_m55/gnu/src/tx_thread_secure_stack_allocate.S
    ${THREADX_ROOT}/ports/cortex_m55/gnu/src/tx_thread_secure_stack_free.S
    ${THREADX_ROOT}/ports/cortex_m55/gnu/src/tx_thread_context_restore.S
    ${THREADX_ROOT}/ports/cortex_m55/gnu/src/tx_thread_context_save.S
    ${THREADX_ROOT}/ports/cortex_m55/gnu/src/tx_thread_interrupt_control.S
    ${THREADX_ROOT}/ports/cortex_m55/gnu/src/tx_thread_interrupt_disable.S
    ${THREADX_ROOT}/ports/cortex_m55/gnu/src/tx_thread_interrupt_restore.S
    ${THREADX_ROOT}/ports/cortex_m55/gnu/src/tx_thread_schedule.S
    ${THREADX_ROOT}/ports/cortex_m55/gnu/src/tx_thread_stack_build.S
    ${THREADX_ROOT}/ports/cortex_m55/gnu/src/tx_thread_system_return.S
    ${THREADX_ROOT}/ports/cortex_m55/gnu/src/tx_timer_interrupt.S
    ${THREADX_ROOT}/ports/cortex_m55/gnu/src/tx_thread_secure_stack.c
    ${THREADX_ROOT}/ports/cortex_m55/gnu/src/txe_thread_secure_stack_free.c
    ${THREADX_ROOT}/ports/cortex_m55/gnu/src/txe_thread_secure_stack_allocate.c

    ${THREADX_ROOT}/common/src/tx_initialize_high_level.c
    ${THREADX_ROOT}/common/src/tx_initialize_kernel_enter.c
    ${THREADX_ROOT}/common/src/tx_initialize_kernel_setup.c
    ${THREADX_ROOT}/common/src/tx_thread_stack_error_handler.c
    ${THREADX_ROOT}/common/src/tx_thread_stack_error_notify.c
    ${THREADX_ROOT}/common/src/tx_thread_system_resume.c
    ${THREADX_ROOT}/common/src/tx_block_allocate.c
    ${THREADX_ROOT}/common/src/tx_block_pool_cleanup.c
    ${THREADX_ROOT}/common/src/tx_block_pool_create.c
    ${THREADX_ROOT}/common/src/tx_block_pool_delete.c
    ${THREADX_ROOT}/common/src/tx_block_pool_info_get.c
    ${THREADX_ROOT}/common/src/tx_block_pool_initialize.c
    ${THREADX_ROOT}/common/src/tx_block_pool_prioritize.c
    ${THREADX_ROOT}/common/src/tx_block_release.c
    ${THREADX_ROOT}/common/src/tx_byte_allocate.c
    ${THREADX_ROOT}/common/src/tx_byte_pool_cleanup.c
    ${THREADX_ROOT}/common/src/tx_byte_pool_create.c
    ${THREADX_ROOT}/common/src/tx_byte_pool_delete.c
    ${THREADX_ROOT}/common/src/tx_byte_pool_info_get.c
    ${THREADX_ROOT}/common/src/tx_byte_pool_initialize.c
    ${THREADX_ROOT}/common/src/tx_byte_pool_prioritize.c
    ${THREADX_ROOT}/common/src/tx_byte_pool_search.c
    ${THREADX_ROOT}/common/src/tx_byte_release.c
    ${THREADX_ROOT}/common/src/tx_event_flags_cleanup.c
    ${THREADX_ROOT}/common/src/tx_event_flags_create.c
    ${THREADX_ROOT}/common/src/tx_event_flags_delete.c
    ${THREADX_ROOT}/common/src/tx_event_flags_get.c
    ${THREADX_ROOT}/common/src/tx_event_flags_info_get.c
    ${THREADX_ROOT}/common/src/tx_event_flags_initialize.c
    ${THREADX_ROOT}/common/src/tx_event_flags_set.c
    ${THREADX_ROOT}/common/src/tx_event_flags_set_notify.c
    ${THREADX_ROOT}/common/src/tx_mutex_cleanup.c
    ${THREADX_ROOT}/common/src/tx_mutex_create.c
    ${THREADX_ROOT}/common/src/tx_mutex_delete.c
    ${THREADX_ROOT}/common/src/tx_mutex_get.c
    ${THREADX_ROOT}/common/src/tx_mutex_info_get.c
    ${THREADX_ROOT}/common/src/tx_mutex_initialize.c
    ${THREADX_ROOT}/common/src/tx_mutex_prioritize.c
    ${THREADX_ROOT}/common/src/tx_mutex_priority_change.c
    ${THREADX_ROOT}/common/src/tx_mutex_put.c
    ${THREADX_ROOT}/common/src/tx_queue_cleanup.c
    ${THREADX_ROOT}/common/src/tx_queue_create.c
    ${THREADX_ROOT}/common/src/tx_queue_delete.c
    ${THREADX_ROOT}/common/src/tx_queue_flush.c
    ${THREADX_ROOT}/common/src/tx_queue_front_send.c
    ${THREADX_ROOT}/common/src/tx_queue_info_get.c
    ${THREADX_ROOT}/common/src/tx_queue_initialize.c
    ${THREADX_ROOT}/common/src/tx_queue_prioritize.c
    ${THREADX_ROOT}/common/src/tx_queue_receive.c
    ${THREADX_ROOT}/common/src/tx_queue_send.c
    ${THREADX_ROOT}/common/src/tx_queue_send_notify.c
    ${THREADX_ROOT}/common/src/tx_semaphore_ceiling_put.c
    ${THREADX_ROOT}/common/src/tx_semaphore_cleanup.c
    ${THREADX_ROOT}/common/src/tx_semaphore_create.c
    ${THREADX_ROOT}/common/src/tx_semaphore_delete.c
    ${THREADX_ROOT}/common/src/tx_semaphore_get.c
    ${THREADX_ROOT}/common/src/tx_semaphore_info_get.c
    ${THREADX_ROOT}/common/src/tx_semaphore_initialize.c
    ${THREADX_ROOT}/common/src/tx_semaphore_prioritize.c
    ${THREADX_ROOT}/common/src/tx_semaphore_put.c
    ${THREADX_ROOT}/common/src/tx_semaphore_put_notify.c
    ${THREADX_ROOT}/common/src/tx_thread_create.c
    ${THREADX_ROOT}/common/src/tx_thread_delete.c
    ${THREADX_ROOT}/common/src/tx_thread_entry_exit_notify.c
    ${THREADX_ROOT}/common/src/tx_thread_identify.c
    ${THREADX_ROOT}/common/src/tx_thread_info_get.c
    ${THREADX_ROOT}/common/src/tx_thread_initialize.c
    ${THREADX_ROOT}/common/src/tx_thread_preemption_change.c
    ${THREADX_ROOT}/common/src/tx_thread_priority_change.c
    ${THREADX_ROOT}/common/src/tx_thread_relinquish.c
    ${THREADX_ROOT}/common/src/tx_thread_reset.c
    ${THREADX_ROOT}/common/src/tx_thread_resume.c
    ${THREADX_ROOT}/common/src/tx_thread_shell_entry.c
    ${THREADX_ROOT}/common/src/tx_thread_sleep.c
    ${THREADX_ROOT}/common/src/tx_thread_stack_analyze.c
    ${THREADX_ROOT}/common/src/tx_thread_suspend.c
    ${THREADX_ROOT}/common/src/tx_thread_system_preempt_check.c
    ${THREADX_ROOT}/common/src/tx_thread_system_suspend.c
    ${THREADX_ROOT}/common/src/tx_thread_terminate.c
    ${THREADX_ROOT}/common/src/tx_thread_time_slice.c
    ${THREADX_ROOT}/common/src/tx_thread_time_slice_change.c
    ${THREADX_ROOT}/common/src/tx_thread_timeout.c
    ${THREADX_ROOT}/common/src/tx_thread_wait_abort.c
    ${THREADX_ROOT}/common/src/tx_time_get.c
    ${THREADX_ROOT}/common/src/tx_time_set.c
    ${THREADX_ROOT}/common/src/txe_block_allocate.c
    ${THREADX_ROOT}/common/src/txe_block_pool_create.c
    ${THREADX_ROOT}/common/src/txe_block_pool_delete.c
    ${THREADX_ROOT}/common/src/txe_block_pool_info_get.c
    ${THREADX_ROOT}/common/src/txe_block_pool_prioritize.c
    ${THREADX_ROOT}/common/src/txe_block_release.c
    ${THREADX_ROOT}/common/src/txe_byte_allocate.c
    ${THREADX_ROOT}/common/src/txe_byte_pool_create.c
    ${THREADX_ROOT}/common/src/txe_byte_pool_delete.c
    ${THREADX_ROOT}/common/src/txe_byte_pool_info_get.c
    ${THREADX_ROOT}/common/src/txe_byte_pool_prioritize.c
    ${THREADX_ROOT}/common/src/txe_byte_release.c
    ${THREADX_ROOT}/common/src/txe_event_flags_create.c
    ${THREADX_ROOT}/common/src/txe_event_flags_delete.c
    ${THREADX_ROOT}/common/src/txe_event_flags_get.c
    ${THREADX_ROOT}/common/src/txe_event_flags_info_get.c
    ${THREADX_ROOT}/common/src/txe_event_flags_set.c
    ${THREADX_ROOT}/common/src/txe_event_flags_set_notify.c
    ${THREADX_ROOT}/common/src/txe_mutex_create.c
    ${THREADX_ROOT}/common/src/txe_mutex_delete.c
    ${THREADX_ROOT}/common/src/txe_mutex_get.c
    ${THREADX_ROOT}/common/src/txe_mutex_info_get.c
    ${THREADX_ROOT}/common/src/txe_mutex_prioritize.c
    ${THREADX_ROOT}/common/src/txe_mutex_put.c
    ${THREADX_ROOT}/common/src/txe_queue_create.c
    ${THREADX_ROOT}/common/src/txe_queue_delete.c
    ${THREADX_ROOT}/common/src/txe_queue_flush.c
    ${THREADX_ROOT}/common/src/txe_queue_front_send.c
    ${THREADX_ROOT}/common/src/txe_queue_info_get.c
    ${THREADX_ROOT}/common/src/txe_queue_prioritize.c
    ${THREADX_ROOT}/common/src/txe_queue_receive.c
    ${THREADX_ROOT}/common/src/txe_queue_send.c
    ${THREADX_ROOT}/common/src/txe_queue_send_notify.c
    ${THREADX_ROOT}/common/src/txe_semaphore_ceiling_put.c
    ${THREADX_ROOT}/common/src/txe_semaphore_create.c
    ${THREADX_ROOT}/common/src/txe_semaphore_delete.c
    ${THREADX_ROOT}/common/src/txe_semaphore_get.c
    ${THREADX_ROOT}/common/src/txe_semaphore_info_get.c
    ${THREADX_ROOT}/common/src/txe_semaphore_prioritize.c
    ${THREADX_ROOT}/common/src/txe_semaphore_put.c
    ${THREADX_ROOT}/common/src/txe_semaphore_put_notify.c
    ${THREADX_ROOT}/common/src/txe_thread_create.c
    ${THREADX_ROOT}/common/src/txe_thread_delete.c
    ${THREADX_ROOT}/common/src/txe_thread_entry_exit_notify.c
    ${THREADX_ROOT}/common/src/txe_thread_info_get.c
    ${THREADX_ROOT}/common/src/txe_thread_preemption_change.c
    ${THREADX_ROOT}/common/src/txe_thread_priority_change.c
    ${THREADX_ROOT}/common/src/txe_thread_relinquish.c
    ${THREADX_ROOT}/common/src/txe_thread_reset.c
    ${THREADX_ROOT}/common/src/txe_thread_resume.c
    ${THREADX_ROOT}/common/src/txe_thread_suspend.c
    ${THREADX_ROOT}/common/src/txe_thread_terminate.c
    ${THREADX_ROOT}/common/src/txe_thread_time_slice_change.c
    ${THREADX_ROOT}/common/src/txe_thread_wait_abort.c
    ${THREADX_ROOT}/common/src/tx_timer_activate.c
    ${THREADX_ROOT}/common/src/tx_timer_change.c
    ${THREADX_ROOT}/common/src/tx_timer_create.c
    ${THREADX_ROOT}/common/src/tx_timer_deactivate.c
    ${THREADX_ROOT}/common/src/tx_timer_delete.c
    ${THREADX_ROOT}/common/src/tx_timer_expiration_process.c
    ${THREADX_ROOT}/common/src/tx_timer_info_get.c
    ${THREADX_ROOT}/common/src/tx_timer_initialize.c
    ${THREADX_ROOT}/common/src/tx_timer_system_activate.c
    ${THREADX_ROOT}/common/src/tx_timer_system_deactivate.c
    ${THREADX_ROOT}/common/src/tx_timer_thread_entry.c
    ${THREADX_ROOT}/common/src/txe_timer_activate.c
    ${THREADX_ROOT}/common/src/txe_timer_change.c
    ${THREADX_ROOT}/common/src/txe_timer_create.c
    ${THREADX_ROOT}/common/src/txe_timer_deactivate.c
    ${THREADX_ROOT}/common/src/txe_timer_delete.c
    ${THREADX_ROOT}/common/src/txe_timer_info_get.c
)

target_include_directories(
  stm32_interface
  INTERFACE
    ${THREADX_ROOT}/common/inc
    ${THREADX_ROOT}/ports/cortex_m55/gnu/inc)

add_library(threadx STATIC ${THREADX_SOURCES})
target_link_libraries(threadx PUBLIC stm32_interface)
