# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x1a\x0cnanopb.proto\"a\n\x06Timing\x12\x14\n\x0cinference_ms\x18\x01 \x01(\r\x12\x16\n\x0epostprocess_ms\x18\x02 \x01(\r\x12\x14\n\x0cnn_period_ms\x18\x03 \x01(\r\x12\x13\n\x0bslow_frames\x18\x04 \x01(\r\"q\n\tDetection\x12\x10\n\x08x_center\x18\x01 \x01(\x02\x12\x10\n\x08y_center\x18\x02 \x01(\x02\x12\r\n\x05width\x18\x03 \x01(\x02\x12\x0e\n\x06height\x18\x04 \x01(\x02\x12\x0c\n\x04\x63onf\x18\x05 \x01(\x02\x12\x13\n\x0b\x63lass_index\x18\x06 \x01(\x05\"d\n\x0f\x44\x65tectionResult\x12\x11\n\ttimestamp\x18\x01 \x01(\r\x12\x17\n\x06timing\x18\x02 \x01(\x0b\x32\x07.Timing\x12%\n\ndetections\x18\x03 \x03(\x0b\x32\n.DetectionB\x05\x92?\x02\x10\n\"\xe1\x01\n\nDeviceInfo\x12\x15\n\rdisplay_width\x18\x01 \x01(\r\x12\x16\n\x0e\x64isplay_height\x18\x02 \x01(\r\x12\x17\n\x0fletterbox_width\x18\x03 \x01(\r\x12\x18\n\x10letterbox_height\x18\x04 \x01(\r\x12\x10\n\x08nn_width\x18\x05 \x01(\r\x12\x11\n\tnn_height\x18\x06 \x01(\r\x12\x19\n\nmodel_name\x18\x07 \x01(\tB\x05\x92?\x02\x08@\x12\x1d\n\x0c\x63lass_labels\x18\x08 \x03(\tB\x07\x92?\x04\x08 \x10\n\x12\x12\n\ncommand_id\x18\t \x01(\r\"*\n\x03\x41\x63k\x12\x12\n\ncommand_id\x18\x01 \x01(\r\x12\x0f\n\x07success\x18\x02 \x01(\x08\"$\n\x11SetDisplayEnabled\x12\x0f\n\x07\x65nabled\x18\x01 \x01(\x08\"\x0f\n\rGetDeviceInfo\"\x81\x01\n\rDeviceMessage\x12,\n\x10\x64\x65tection_result\x18\x01 \x01(\x0b\x32\x10.DetectionResultH\x00\x12\"\n\x0b\x64\x65vice_info\x18\x02 \x01(\x0b\x32\x0b.DeviceInfoH\x00\x12\x13\n\x03\x61\x63k\x18\x03 \x01(\x0b\x32\x04.AckH\x00\x42\t\n\x07payload\"\x8a\x01\n\x0bHostMessage\x12\x12\n\ncommand_id\x18\x01 \x01(\r\x12\x31\n\x13set_display_enabled\x18\x02 \x01(\x0b\x32\x12.SetDisplayEnabledH\x00\x12)\n\x0fget_device_info\x18\x03 \x01(\x0b\x32\x0e.GetDeviceInfoH\x00\x42\t\n\x07\x63ommandb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DETECTIONRESULT'].fields_by_name['detections']._loaded_options = None
  _globals['_DETECTIONRESULT'].fields_by_name['detections']._serialized_options = b'\222?\002\020\n'
  _globals['_DEVICEINFO'].fields_by_name['model_name']._loaded_options = None
  _globals['_DEVICEINFO'].fields_by_name['model_name']._serialized_options = b'\222?\002\010@'
  _globals['_DEVICEINFO'].fields_by_name['class_labels']._loaded_options = None
  _globals['_DEVICEINFO'].fields_by_name['class_labels']._serialized_options = b'\222?\004\010 \020\n'
  _globals['_TIMING']._serialized_start=32
  _globals['_TIMING']._serialized_end=129
  _globals['_DETECTION']._serialized_start=131
  _globals['_DETECTION']._serialized_end=244
  _globals['_DETECTIONRESULT']._serialized_start=246
  _globals['_DETECTIONRESULT']._serialized_end=346
  _globals['_DEVICEINFO']._serialized_start=349
  _globals['_DEVICEINFO']._serialized_end=574
  _globals['_ACK']._serialized_start=576
  _globals['_ACK']._serialized_end=618
  _globals['_SETDISPLAYENABLED']._serialized_start=620
  _globals['_SETDISPLAYENABLED']._serialized_end=656
  _globals['_GETDEVICEINFO']._serialized_start=658
  _globals['_GETDEVICEINFO']._serialized_end=673
  _globals['_DEVICEMESSAGE']._serialized_start=676
  _globals['_DEVICEMESSAGE']._serialized_end=805
  _globals['_HOSTMESSAGE']._serialized_start=808
  _globals['_HOSTMESSAGE']._serialized_end=946
# @@protoc_insertion_point(module_scope)
