/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_MESSAGES_PB_H_INCLUDED
#define PB_MESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Timing {
    uint32_t inference_ms;
    uint32_t postprocess_ms;
    uint32_t nn_period_ms;
    uint32_t frame_drops;
} Timing;

typedef struct _Detection {
    float x_center;
    float y_center;
    float width;
    float height;
    float conf;
    int32_t class_index;
} Detection;

typedef struct _DetectionResult {
    uint32_t timestamp;
    bool has_timing;
    Timing timing;
    pb_size_t detections_count;
    Detection detections[10];
} DetectionResult;

typedef PB_BYTES_ARRAY_T(1024) ImageTransfer_pixel_data_t;
typedef struct _ImageTransfer {
    uint32_t width;
    uint32_t height;
    uint32_t channels;
    ImageTransfer_pixel_data_t pixel_data;
} ImageTransfer;

typedef struct _DatalogMessage {
    pb_size_t which_payload;
    union _DatalogMessage_payload {
        DetectionResult detection_result;
        ImageTransfer image_transfer;
    } payload;
} DatalogMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Timing_init_default                      {0, 0, 0, 0}
#define Detection_init_default                   {0, 0, 0, 0, 0, 0}
#define DetectionResult_init_default             {0, false, Timing_init_default, 0, {Detection_init_default, Detection_init_default, Detection_init_default, Detection_init_default, Detection_init_default, Detection_init_default, Detection_init_default, Detection_init_default, Detection_init_default, Detection_init_default}}
#define ImageTransfer_init_default               {0, 0, 0, {0, {0}}}
#define DatalogMessage_init_default              {0, {DetectionResult_init_default}}
#define Timing_init_zero                         {0, 0, 0, 0}
#define Detection_init_zero                      {0, 0, 0, 0, 0, 0}
#define DetectionResult_init_zero                {0, false, Timing_init_zero, 0, {Detection_init_zero, Detection_init_zero, Detection_init_zero, Detection_init_zero, Detection_init_zero, Detection_init_zero, Detection_init_zero, Detection_init_zero, Detection_init_zero, Detection_init_zero}}
#define ImageTransfer_init_zero                  {0, 0, 0, {0, {0}}}
#define DatalogMessage_init_zero                 {0, {DetectionResult_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define Timing_inference_ms_tag                  1
#define Timing_postprocess_ms_tag                2
#define Timing_nn_period_ms_tag                  3
#define Timing_frame_drops_tag                   4
#define Detection_x_center_tag                   1
#define Detection_y_center_tag                   2
#define Detection_width_tag                      3
#define Detection_height_tag                     4
#define Detection_conf_tag                       5
#define Detection_class_index_tag                6
#define DetectionResult_timestamp_tag            1
#define DetectionResult_timing_tag               2
#define DetectionResult_detections_tag           3
#define ImageTransfer_width_tag                  1
#define ImageTransfer_height_tag                 2
#define ImageTransfer_channels_tag               3
#define ImageTransfer_pixel_data_tag             4
#define DatalogMessage_detection_result_tag      1
#define DatalogMessage_image_transfer_tag        2

/* Struct field encoding specification for nanopb */
#define Timing_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   inference_ms,      1) \
X(a, STATIC,   SINGULAR, UINT32,   postprocess_ms,    2) \
X(a, STATIC,   SINGULAR, UINT32,   nn_period_ms,      3) \
X(a, STATIC,   SINGULAR, UINT32,   frame_drops,       4)
#define Timing_CALLBACK NULL
#define Timing_DEFAULT NULL

#define Detection_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x_center,          1) \
X(a, STATIC,   SINGULAR, FLOAT,    y_center,          2) \
X(a, STATIC,   SINGULAR, FLOAT,    width,             3) \
X(a, STATIC,   SINGULAR, FLOAT,    height,            4) \
X(a, STATIC,   SINGULAR, FLOAT,    conf,              5) \
X(a, STATIC,   SINGULAR, INT32,    class_index,       6)
#define Detection_CALLBACK NULL
#define Detection_DEFAULT NULL

#define DetectionResult_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp,         1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  timing,            2) \
X(a, STATIC,   REPEATED, MESSAGE,  detections,        3)
#define DetectionResult_CALLBACK NULL
#define DetectionResult_DEFAULT NULL
#define DetectionResult_timing_MSGTYPE Timing
#define DetectionResult_detections_MSGTYPE Detection

#define ImageTransfer_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   width,             1) \
X(a, STATIC,   SINGULAR, UINT32,   height,            2) \
X(a, STATIC,   SINGULAR, UINT32,   channels,          3) \
X(a, STATIC,   SINGULAR, BYTES,    pixel_data,        4)
#define ImageTransfer_CALLBACK NULL
#define ImageTransfer_DEFAULT NULL

#define DatalogMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,detection_result,payload.detection_result),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,image_transfer,payload.image_transfer),   2)
#define DatalogMessage_CALLBACK NULL
#define DatalogMessage_DEFAULT NULL
#define DatalogMessage_payload_detection_result_MSGTYPE DetectionResult
#define DatalogMessage_payload_image_transfer_MSGTYPE ImageTransfer

extern const pb_msgdesc_t Timing_msg;
extern const pb_msgdesc_t Detection_msg;
extern const pb_msgdesc_t DetectionResult_msg;
extern const pb_msgdesc_t ImageTransfer_msg;
extern const pb_msgdesc_t DatalogMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Timing_fields &Timing_msg
#define Detection_fields &Detection_msg
#define DetectionResult_fields &DetectionResult_msg
#define ImageTransfer_fields &ImageTransfer_msg
#define DatalogMessage_fields &DatalogMessage_msg

/* Maximum encoded size of messages (where known) */
#define DatalogMessage_size                      1048
#define DetectionResult_size                     412
#define Detection_size                           36
#define ImageTransfer_size                       1045
#define MESSAGES_PB_H_MAX_SIZE                   DatalogMessage_size
#define Timing_size                              24

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
