/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Timing, Timing, AUTO)


PB_BIND(Detection, Detection, AUTO)


PB_BIND(DetectionResult, DetectionResult, 2)


PB_BIND(ImageTransfer, ImageTransfer, 2)


PB_BIND(DatalogMessage, DatalogMessage, 2)



