/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Timing, Timing, AUTO)


PB_BIND(Detection, Detection, AUTO)


PB_BIND(TofAlert, TofAlert, 2)


PB_BIND(CpuLoad, CpuLoad, AUTO)


PB_BIND(DetectionResult, DetectionResult, 2)


PB_BIND(DeviceInfo, DeviceInfo, 2)


PB_BIND(Ack, Ack, AUTO)


PB_BIND(TraceXChunk, TraceXChunk, 2)


PB_BIND(SetDisplayEnabled, SetDisplayEnabled, AUTO)


PB_BIND(GetDeviceInfo, GetDeviceInfo, AUTO)


PB_BIND(GetTraceXDump, GetTraceXDump, AUTO)


PB_BIND(DeviceMessage, DeviceMessage, 2)


PB_BIND(HostMessage, HostMessage, AUTO)



