/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_MESSAGES_PB_H_INCLUDED
#define PB_MESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Normalized box in [0,1]; class_id is the model class index. */
typedef struct _Detection {
    float x;
    float y;
    float w;
    float h;
    float score;
    uint32_t class_id;
} Detection;

typedef struct _TrackedBox {
    float x;
    float y;
    float w;
    float h;
    uint32_t track_id;
} TrackedBox;

/* flags: bit0 = proximity alert, bit1 = measurement stale.
 depth_mm: row-major 8x8, millimeters (sensor-native range). */
typedef struct _TofAlert {
    uint32_t hand_mm;
    uint32_t hazard_mm;
    uint32_t flags;
    float distance_3d_mm;
    pb_size_t depth_mm_count;
    int32_t depth_mm[64];
} TofAlert;

/* Timing fields are inlined (no submessage) to avoid extra protobuf length
 delimiters and nanopb has_* submessage flags on the hot path. */
typedef struct _DetectionResult {
    uint32_t sent_timestamp_ms;
    uint32_t frame_timestamp_ms;
    uint32_t inference_us;
    uint32_t postprocess_us;
    uint32_t nn_period_us;
    uint32_t frame_drop_count;
    uint32_t tracker_us;
    float cpu_usage_percent;
    pb_size_t detections_count;
    Detection detections[10];
    pb_size_t tracks_count;
    TrackedBox tracks[10];
    bool has_tof;
    TofAlert tof;
} DetectionResult;

/* Scalar fields first for compact C struct layout; strings last. */
typedef struct _DeviceInfo {
    uint32_t timestamp_ms;
    uint32_t display_width_px;
    uint32_t display_height_px;
    uint32_t letterbox_width_px;
    uint32_t letterbox_height_px;
    uint32_t nn_width_px;
    uint32_t nn_height_px;
    uint32_t nn_input_size_bytes;
    uint32_t power_mode;
    uint32_t camera_fps;
    uint32_t mcu_freq_mhz;
    uint32_t npu_freq_mhz;
    char model_name[64];
    pb_size_t class_labels_count;
    char class_labels[10][32];
    char build_timestamp[24];
    float pp_conf_threshold;
    float pp_iou_threshold;
    float track_thresh;
    float det_thresh;
    float sim1_thresh;
    float sim2_thresh;
    uint32_t tlost_cnt;
} DeviceInfo;

typedef struct _Ack {
    bool success;
    uint32_t timestamp_ms;
} Ack;

typedef PB_BYTES_ARRAY_T(256) TraceXChunk_data_t;
typedef struct _TraceXChunk {
    uint32_t offset_bytes;
    uint32_t total_size_bytes;
    TraceXChunk_data_t data;
    bool done;
    uint32_t timestamp_ms;
} TraceXChunk;

typedef struct _SetDisplayEnabled {
    bool enabled;
    uint32_t timestamp_ms;
} SetDisplayEnabled;

typedef struct _GetDeviceInfo {
    uint32_t timestamp_ms;
} GetDeviceInfo;

typedef struct _GetTraceXDump {
    uint32_t chunk_size_bytes;
    uint32_t timestamp_ms;
} GetTraceXDump;

typedef struct _SetPostprocessConfig {
    float pp_conf_threshold;
    float pp_iou_threshold;
    float track_thresh;
    float det_thresh;
    float sim1_thresh;
    float sim2_thresh;
    uint32_t tlost_cnt;
    uint32_t timestamp_ms;
} SetPostprocessConfig;

typedef struct _DeviceMessage {
    pb_size_t which_payload;
    union _DeviceMessage_payload {
        DetectionResult detection_result;
        DeviceInfo device_info;
        Ack ack;
        TraceXChunk tracex_chunk;
    } payload;
} DeviceMessage;

typedef struct _HostMessage {
    pb_size_t which_command;
    union _HostMessage_command {
        SetDisplayEnabled set_display_enabled;
        GetDeviceInfo get_device_info;
        GetTraceXDump get_tracex_dump;
        SetPostprocessConfig set_postprocess_config;
    } command;
} HostMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Detection_init_default                   {0, 0, 0, 0, 0, 0}
#define TrackedBox_init_default                  {0, 0, 0, 0, 0}
#define TofAlert_init_default                    {0, 0, 0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define DetectionResult_init_default             {0, 0, 0, 0, 0, 0, 0, 0, 0, {Detection_init_default, Detection_init_default, Detection_init_default, Detection_init_default, Detection_init_default, Detection_init_default, Detection_init_default, Detection_init_default, Detection_init_default, Detection_init_default}, 0, {TrackedBox_init_default, TrackedBox_init_default, TrackedBox_init_default, TrackedBox_init_default, TrackedBox_init_default, TrackedBox_init_default, TrackedBox_init_default, TrackedBox_init_default, TrackedBox_init_default, TrackedBox_init_default}, false, TofAlert_init_default}
#define DeviceInfo_init_default                  {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "", 0, {"", "", "", "", "", "", "", "", "", ""}, "", 0, 0, 0, 0, 0, 0, 0}
#define Ack_init_default                         {0, 0}
#define TraceXChunk_init_default                 {0, 0, {0, {0}}, 0, 0}
#define SetDisplayEnabled_init_default           {0, 0}
#define GetDeviceInfo_init_default               {0}
#define GetTraceXDump_init_default               {0, 0}
#define SetPostprocessConfig_init_default        {0, 0, 0, 0, 0, 0, 0, 0}
#define DeviceMessage_init_default               {0, {DetectionResult_init_default}}
#define HostMessage_init_default                 {0, {SetDisplayEnabled_init_default}}
#define Detection_init_zero                      {0, 0, 0, 0, 0, 0}
#define TrackedBox_init_zero                     {0, 0, 0, 0, 0}
#define TofAlert_init_zero                       {0, 0, 0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define DetectionResult_init_zero                {0, 0, 0, 0, 0, 0, 0, 0, 0, {Detection_init_zero, Detection_init_zero, Detection_init_zero, Detection_init_zero, Detection_init_zero, Detection_init_zero, Detection_init_zero, Detection_init_zero, Detection_init_zero, Detection_init_zero}, 0, {TrackedBox_init_zero, TrackedBox_init_zero, TrackedBox_init_zero, TrackedBox_init_zero, TrackedBox_init_zero, TrackedBox_init_zero, TrackedBox_init_zero, TrackedBox_init_zero, TrackedBox_init_zero, TrackedBox_init_zero}, false, TofAlert_init_zero}
#define DeviceInfo_init_zero                     {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "", 0, {"", "", "", "", "", "", "", "", "", ""}, "", 0, 0, 0, 0, 0, 0, 0}
#define Ack_init_zero                            {0, 0}
#define TraceXChunk_init_zero                    {0, 0, {0, {0}}, 0, 0}
#define SetDisplayEnabled_init_zero              {0, 0}
#define GetDeviceInfo_init_zero                  {0}
#define GetTraceXDump_init_zero                  {0, 0}
#define SetPostprocessConfig_init_zero           {0, 0, 0, 0, 0, 0, 0, 0}
#define DeviceMessage_init_zero                  {0, {DetectionResult_init_zero}}
#define HostMessage_init_zero                    {0, {SetDisplayEnabled_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define Detection_x_tag                          1
#define Detection_y_tag                          2
#define Detection_w_tag                          3
#define Detection_h_tag                          4
#define Detection_score_tag                      5
#define Detection_class_id_tag                   6
#define TrackedBox_x_tag                         1
#define TrackedBox_y_tag                         2
#define TrackedBox_w_tag                         3
#define TrackedBox_h_tag                         4
#define TrackedBox_track_id_tag                  5
#define TofAlert_hand_mm_tag                     1
#define TofAlert_hazard_mm_tag                   2
#define TofAlert_flags_tag                       3
#define TofAlert_distance_3d_mm_tag              4
#define TofAlert_depth_mm_tag                    5
#define DetectionResult_sent_timestamp_ms_tag    1
#define DetectionResult_frame_timestamp_ms_tag   2
#define DetectionResult_inference_us_tag         3
#define DetectionResult_postprocess_us_tag       4
#define DetectionResult_nn_period_us_tag         5
#define DetectionResult_frame_drop_count_tag     6
#define DetectionResult_tracker_us_tag           7
#define DetectionResult_cpu_usage_percent_tag    8
#define DetectionResult_detections_tag           9
#define DetectionResult_tracks_tag               10
#define DetectionResult_tof_tag                  11
#define DeviceInfo_timestamp_ms_tag              1
#define DeviceInfo_display_width_px_tag          2
#define DeviceInfo_display_height_px_tag         3
#define DeviceInfo_letterbox_width_px_tag        4
#define DeviceInfo_letterbox_height_px_tag       5
#define DeviceInfo_nn_width_px_tag               6
#define DeviceInfo_nn_height_px_tag              7
#define DeviceInfo_nn_input_size_bytes_tag       8
#define DeviceInfo_power_mode_tag                9
#define DeviceInfo_camera_fps_tag                10
#define DeviceInfo_mcu_freq_mhz_tag              11
#define DeviceInfo_npu_freq_mhz_tag              12
#define DeviceInfo_model_name_tag                13
#define DeviceInfo_class_labels_tag              14
#define DeviceInfo_build_timestamp_tag           15
#define DeviceInfo_pp_conf_threshold_tag         16
#define DeviceInfo_pp_iou_threshold_tag          17
#define DeviceInfo_track_thresh_tag              18
#define DeviceInfo_det_thresh_tag                19
#define DeviceInfo_sim1_thresh_tag               20
#define DeviceInfo_sim2_thresh_tag               21
#define DeviceInfo_tlost_cnt_tag                 22
#define Ack_success_tag                          1
#define Ack_timestamp_ms_tag                     2
#define TraceXChunk_offset_bytes_tag             1
#define TraceXChunk_total_size_bytes_tag         2
#define TraceXChunk_data_tag                     3
#define TraceXChunk_done_tag                     4
#define TraceXChunk_timestamp_ms_tag             5
#define SetDisplayEnabled_enabled_tag            1
#define SetDisplayEnabled_timestamp_ms_tag       2
#define GetDeviceInfo_timestamp_ms_tag           1
#define GetTraceXDump_chunk_size_bytes_tag       1
#define GetTraceXDump_timestamp_ms_tag           2
#define SetPostprocessConfig_pp_conf_threshold_tag 1
#define SetPostprocessConfig_pp_iou_threshold_tag 2
#define SetPostprocessConfig_track_thresh_tag    3
#define SetPostprocessConfig_det_thresh_tag      4
#define SetPostprocessConfig_sim1_thresh_tag     5
#define SetPostprocessConfig_sim2_thresh_tag     6
#define SetPostprocessConfig_tlost_cnt_tag       7
#define SetPostprocessConfig_timestamp_ms_tag    8
#define DeviceMessage_detection_result_tag       1
#define DeviceMessage_device_info_tag            2
#define DeviceMessage_ack_tag                    3
#define DeviceMessage_tracex_chunk_tag           4
#define HostMessage_set_display_enabled_tag      1
#define HostMessage_get_device_info_tag          2
#define HostMessage_get_tracex_dump_tag          3
#define HostMessage_set_postprocess_config_tag   4

/* Struct field encoding specification for nanopb */
#define Detection_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    w,                 3) \
X(a, STATIC,   SINGULAR, FLOAT,    h,                 4) \
X(a, STATIC,   SINGULAR, FLOAT,    score,             5) \
X(a, STATIC,   SINGULAR, UINT32,   class_id,          6)
#define Detection_CALLBACK NULL
#define Detection_DEFAULT NULL

#define TrackedBox_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    w,                 3) \
X(a, STATIC,   SINGULAR, FLOAT,    h,                 4) \
X(a, STATIC,   SINGULAR, UINT32,   track_id,          5)
#define TrackedBox_CALLBACK NULL
#define TrackedBox_DEFAULT NULL

#define TofAlert_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   hand_mm,           1) \
X(a, STATIC,   SINGULAR, UINT32,   hazard_mm,         2) \
X(a, STATIC,   SINGULAR, UINT32,   flags,             3) \
X(a, STATIC,   SINGULAR, FLOAT,    distance_3d_mm,    4) \
X(a, STATIC,   REPEATED, INT32,    depth_mm,          5)
#define TofAlert_CALLBACK NULL
#define TofAlert_DEFAULT NULL

#define DetectionResult_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sent_timestamp_ms,   1) \
X(a, STATIC,   SINGULAR, UINT32,   frame_timestamp_ms,   2) \
X(a, STATIC,   SINGULAR, UINT32,   inference_us,      3) \
X(a, STATIC,   SINGULAR, UINT32,   postprocess_us,    4) \
X(a, STATIC,   SINGULAR, UINT32,   nn_period_us,      5) \
X(a, STATIC,   SINGULAR, UINT32,   frame_drop_count,   6) \
X(a, STATIC,   SINGULAR, UINT32,   tracker_us,        7) \
X(a, STATIC,   SINGULAR, FLOAT,    cpu_usage_percent,   8) \
X(a, STATIC,   REPEATED, MESSAGE,  detections,        9) \
X(a, STATIC,   REPEATED, MESSAGE,  tracks,           10) \
X(a, STATIC,   OPTIONAL, MESSAGE,  tof,              11)
#define DetectionResult_CALLBACK NULL
#define DetectionResult_DEFAULT NULL
#define DetectionResult_detections_MSGTYPE Detection
#define DetectionResult_tracks_MSGTYPE TrackedBox
#define DetectionResult_tof_MSGTYPE TofAlert

#define DeviceInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp_ms,      1) \
X(a, STATIC,   SINGULAR, UINT32,   display_width_px,   2) \
X(a, STATIC,   SINGULAR, UINT32,   display_height_px,   3) \
X(a, STATIC,   SINGULAR, UINT32,   letterbox_width_px,   4) \
X(a, STATIC,   SINGULAR, UINT32,   letterbox_height_px,   5) \
X(a, STATIC,   SINGULAR, UINT32,   nn_width_px,       6) \
X(a, STATIC,   SINGULAR, UINT32,   nn_height_px,      7) \
X(a, STATIC,   SINGULAR, UINT32,   nn_input_size_bytes,   8) \
X(a, STATIC,   SINGULAR, UINT32,   power_mode,        9) \
X(a, STATIC,   SINGULAR, UINT32,   camera_fps,       10) \
X(a, STATIC,   SINGULAR, UINT32,   mcu_freq_mhz,     11) \
X(a, STATIC,   SINGULAR, UINT32,   npu_freq_mhz,     12) \
X(a, STATIC,   SINGULAR, STRING,   model_name,       13) \
X(a, STATIC,   REPEATED, STRING,   class_labels,     14) \
X(a, STATIC,   SINGULAR, STRING,   build_timestamp,  15) \
X(a, STATIC,   SINGULAR, FLOAT,    pp_conf_threshold,  16) \
X(a, STATIC,   SINGULAR, FLOAT,    pp_iou_threshold,  17) \
X(a, STATIC,   SINGULAR, FLOAT,    track_thresh,     18) \
X(a, STATIC,   SINGULAR, FLOAT,    det_thresh,       19) \
X(a, STATIC,   SINGULAR, FLOAT,    sim1_thresh,      20) \
X(a, STATIC,   SINGULAR, FLOAT,    sim2_thresh,      21) \
X(a, STATIC,   SINGULAR, UINT32,   tlost_cnt,        22)
#define DeviceInfo_CALLBACK NULL
#define DeviceInfo_DEFAULT NULL

#define Ack_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp_ms,      2)
#define Ack_CALLBACK NULL
#define Ack_DEFAULT NULL

#define TraceXChunk_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   offset_bytes,      1) \
X(a, STATIC,   SINGULAR, UINT32,   total_size_bytes,   2) \
X(a, STATIC,   SINGULAR, BYTES,    data,              3) \
X(a, STATIC,   SINGULAR, BOOL,     done,              4) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp_ms,      5)
#define TraceXChunk_CALLBACK NULL
#define TraceXChunk_DEFAULT NULL

#define SetDisplayEnabled_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           1) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp_ms,      2)
#define SetDisplayEnabled_CALLBACK NULL
#define SetDisplayEnabled_DEFAULT NULL

#define GetDeviceInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp_ms,      1)
#define GetDeviceInfo_CALLBACK NULL
#define GetDeviceInfo_DEFAULT NULL

#define GetTraceXDump_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   chunk_size_bytes,   1) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp_ms,      2)
#define GetTraceXDump_CALLBACK NULL
#define GetTraceXDump_DEFAULT NULL

#define SetPostprocessConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    pp_conf_threshold,   1) \
X(a, STATIC,   SINGULAR, FLOAT,    pp_iou_threshold,   2) \
X(a, STATIC,   SINGULAR, FLOAT,    track_thresh,      3) \
X(a, STATIC,   SINGULAR, FLOAT,    det_thresh,        4) \
X(a, STATIC,   SINGULAR, FLOAT,    sim1_thresh,       5) \
X(a, STATIC,   SINGULAR, FLOAT,    sim2_thresh,       6) \
X(a, STATIC,   SINGULAR, UINT32,   tlost_cnt,         7) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp_ms,      8)
#define SetPostprocessConfig_CALLBACK NULL
#define SetPostprocessConfig_DEFAULT NULL

#define DeviceMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,detection_result,payload.detection_result),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,device_info,payload.device_info),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ack,payload.ack),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,tracex_chunk,payload.tracex_chunk),   4)
#define DeviceMessage_CALLBACK NULL
#define DeviceMessage_DEFAULT NULL
#define DeviceMessage_payload_detection_result_MSGTYPE DetectionResult
#define DeviceMessage_payload_device_info_MSGTYPE DeviceInfo
#define DeviceMessage_payload_ack_MSGTYPE Ack
#define DeviceMessage_payload_tracex_chunk_MSGTYPE TraceXChunk

#define HostMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,set_display_enabled,command.set_display_enabled),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,get_device_info,command.get_device_info),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,get_tracex_dump,command.get_tracex_dump),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,set_postprocess_config,command.set_postprocess_config),   4)
#define HostMessage_CALLBACK NULL
#define HostMessage_DEFAULT NULL
#define HostMessage_command_set_display_enabled_MSGTYPE SetDisplayEnabled
#define HostMessage_command_get_device_info_MSGTYPE GetDeviceInfo
#define HostMessage_command_get_tracex_dump_MSGTYPE GetTraceXDump
#define HostMessage_command_set_postprocess_config_MSGTYPE SetPostprocessConfig

extern const pb_msgdesc_t Detection_msg;
extern const pb_msgdesc_t TrackedBox_msg;
extern const pb_msgdesc_t TofAlert_msg;
extern const pb_msgdesc_t DetectionResult_msg;
extern const pb_msgdesc_t DeviceInfo_msg;
extern const pb_msgdesc_t Ack_msg;
extern const pb_msgdesc_t TraceXChunk_msg;
extern const pb_msgdesc_t SetDisplayEnabled_msg;
extern const pb_msgdesc_t GetDeviceInfo_msg;
extern const pb_msgdesc_t GetTraceXDump_msg;
extern const pb_msgdesc_t SetPostprocessConfig_msg;
extern const pb_msgdesc_t DeviceMessage_msg;
extern const pb_msgdesc_t HostMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Detection_fields &Detection_msg
#define TrackedBox_fields &TrackedBox_msg
#define TofAlert_fields &TofAlert_msg
#define DetectionResult_fields &DetectionResult_msg
#define DeviceInfo_fields &DeviceInfo_msg
#define Ack_fields &Ack_msg
#define TraceXChunk_fields &TraceXChunk_msg
#define SetDisplayEnabled_fields &SetDisplayEnabled_msg
#define GetDeviceInfo_fields &GetDeviceInfo_msg
#define GetTraceXDump_fields &GetTraceXDump_msg
#define SetPostprocessConfig_fields &SetPostprocessConfig_msg
#define DeviceMessage_fields &DeviceMessage_msg
#define HostMessage_fields &HostMessage_msg

/* Maximum encoded size of messages (where known) */
#define Ack_size                                 8
#define DetectionResult_size                     1387
#define Detection_size                           31
#define DeviceInfo_size                          535
#define DeviceMessage_size                       1390
#define GetDeviceInfo_size                       6
#define GetTraceXDump_size                       12
#define HostMessage_size                         44
#define MESSAGES_PB_H_MAX_SIZE                   DeviceMessage_size
#define SetDisplayEnabled_size                   8
#define SetPostprocessConfig_size                42
#define TofAlert_size                            727
#define TraceXChunk_size                         279
#define TrackedBox_size                          26

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
